### PR TITLE
Skip any .#SomeFile.java from the action

### PR DESCRIPTION
**Pull request by agilecreativity**
Hi @ztellman 

Thanks for the great project. I found that for some reason I keep getting the error when trying to reload the code locally. It seems that virgil will some how find the file `.#JavaFile.java` when I am editing/changing the `JavaFile.java`. This PR is trying to skip this type of files and allow virgil to run properly.

I can consistently replicate it in my two Arch Linux machine so I guess someone else may be encounter the same issue.

I am using Emacs and on the REPL I got something like this when trying this with my simple project [try-virgil](https://github.com/agilecreativity/try-virgil)

```
recompiling all files in /home/bchoomnuan/projects/personal/try-virgil/src/main/java
/home/bchoomnuan/projects/personal/try-virgil/src/main/java/try_virgil/.#SimpleLib.java (No such file or directory)
try_virgil.core> 
```

### CODE REVIEW

**Comment by ztellman** [comment]
I'm tempted to say that this should skip any file starting with `.`, full stop.  At the very least, though, I'd like to have your `.contains` check be a `.startsWith` check.  Otherwise, this is a good addition to the library, thanks.

**Comment by agilecreativity** [comment]
Thanks for you quick response.
I found that the `startsWith` will not work as the file might be at the end of the path e.g. the path might be like `/src/main/java/.#SomeFile.java` if you want that check then the code may be a bit longer.

Instead I just check for `#` in the file name. Would this be sufficient or do you see if we could run into any problem?

**Comment by ztellman** [comment]
I'd suggest using something like https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#getFileName().  I admit it's unlikely someone has a valid `.#` in their path elsewhere, but it's not hard to be precise about this.

**Comment by agilecreativity** [comment]
@ztellman 
Thanks for the suggestion.
I refactored the code a bit more and create new function that can be called in two places.
Hopefully this is ok.
Thanks

**Pull request merged**
